# Generated by Django 5.1.15 on 2026-05-26 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('license_changed', 'License changed'), ('price_changed', 'Price changed'), ('stock_changed', 'Stock changed'), ('status_changed', 'Status changed'), ('channel.published', 'Channel published'), ('channel.unpublished', 'Channel unpublished'), ('channel.sync_failed', 'Channel sync failed'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=64)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'db_table': 'core_audit_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='core_audit__entity__d37758_idx'), models.Index(fields=['actor', '-created_at'], name='core_audit__actor_i_5a675b_idx'), models.Index(fields=['action', '-created_at'], name='core_audit__action_2357b7_idx')],
            },
        ),
    ]
