# Generated by Django 5.1.15 on 2026-05-26 10:12
# Postgres-specific indexes appended dưới CreateModel (xem DESIGN.md §"Database changes").

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Cần extensions (pg_trgm, btree_gin, ...) đã enable trước khi
        # CREATE INDEX USING GIN gin_trgm_ops, jsonb_path_ops.
        ("core", "0002_postgres_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                ("sku_root", models.CharField(max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("short_description", models.TextField(blank=True, default="")),
                ("long_description", models.TextField(blank=True, default="")),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=50,
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "catalog_products",
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(fields=["-updated_at"], name="catalog_products_updated_idx"),
                    models.Index(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=["status"],
                        name="catalog_products_status_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sku_root__regex", "^[A-Z0-9]{3,8}$")),
                        name="catalog_products_sku_root_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["draft", "active", "archived"])),
                        name="catalog_products_status_choices",
                    ),
                ],
            },
        ),
        # ---------------------------------------------------------------
        # Postgres-specific indexes (Django ORM không expose Lower() trong
        # partial unique index một cách thuận tiện ở 5.1, dùng raw SQL).
        # ---------------------------------------------------------------
        # Partial unique index trên LOWER(slug) — chỉ áp row chưa xoá.
        # Cho phép tạo lại slug giống sau soft delete.
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX catalog_products_slug_lower_alive_uq
                ON catalog_products (LOWER(slug))
                WHERE deleted_at IS NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS catalog_products_slug_lower_alive_uq;",
        ),
        # Partial unique index trên LOWER(sku_root) — case-insensitive unique
        # chỉ trong scope alive. AC-3 yêu cầu "DRAGON" == "dragon".
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX catalog_products_sku_root_lower_alive_uq
                ON catalog_products (LOWER(sku_root))
                WHERE deleted_at IS NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS catalog_products_sku_root_lower_alive_uq;",
        ),
        # GIN trgm trên name — phục vụ search icontains hiệu quả.
        # AC-6: search input matching name/sku_root.
        migrations.RunSQL(
            sql="""
                CREATE INDEX catalog_products_name_trgm_idx
                ON catalog_products
                USING GIN (name gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS catalog_products_name_trgm_idx;",
        ),
        # GIN trgm trên sku_root — search input matching cả 2 column.
        migrations.RunSQL(
            sql="""
                CREATE INDEX catalog_products_sku_root_trgm_idx
                ON catalog_products
                USING GIN (sku_root gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS catalog_products_sku_root_trgm_idx;",
        ),
        # GIN jsonb_path_ops trên attributes — query containment @>.
        # Tương lai filter products theo attribute value.
        migrations.RunSQL(
            sql="""
                CREATE INDEX catalog_products_attributes_gin_idx
                ON catalog_products
                USING GIN (attributes jsonb_path_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS catalog_products_attributes_gin_idx;",
        ),
        # GIN trên tags array — query tags @> ARRAY['dragon'].
        migrations.RunSQL(
            sql="""
                CREATE INDEX catalog_products_tags_gin_idx
                ON catalog_products
                USING GIN (tags);
            """,
            reverse_sql="DROP INDEX IF EXISTS catalog_products_tags_gin_idx;",
        ),
    ]
