# Generated by Django 5.1.15 on 2026-06-11 07:42
# Postgres-specific indexes appended dưới CreateModel (xem DESIGN.md §"Indexes").

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        # Cần pg_trgm + jsonb_path_ops + btree_gin extension trước khi
        # CREATE INDEX USING GIN.
        ('core', '0002_postgres_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sku', models.CharField(max_length=24)),
                ('sequence_no', models.PositiveIntegerField()),
                ('material_name', models.CharField(max_length=64)),
                ('material_code3', models.CharField(max_length=4)),
                ('color_name', models.CharField(max_length=64)),
                ('color_code3', models.CharField(max_length=4)),
                ('size_preset', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', related_query_name='variant', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'db_table': 'skus_variants',
                'ordering': ('product', 'sequence_no'),
                'indexes': [models.Index(fields=['product', 'sequence_no'], name='skus_variants_prod_seq_idx'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status'], name='skus_variants_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='skus_variants_base_price_nonneg'), models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='skus_variants_cost_price_nonneg'), models.CheckConstraint(condition=models.Q(('sequence_no__gte', 1)), name='skus_variants_sequence_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'archived'])), name='skus_variants_status_choices'), models.CheckConstraint(condition=models.Q(('material_code3__regex', '^[A-Z0-9]{2,4}$')), name='skus_variants_material_code3_format'), models.CheckConstraint(condition=models.Q(('color_code3__regex', '^[A-Z0-9]{2,4}$')), name='skus_variants_color_code3_format'), models.CheckConstraint(condition=models.Q(('size_preset__regex', '^[A-Za-z0-9]{1,8}$')), name='skus_variants_size_preset_format'), models.CheckConstraint(condition=models.Q(('sku__regex', '^.{12,24}$')), name='skus_variants_sku_length')],
            },
        ),
        # ---------------------------------------------------------------
        # Postgres-specific indexes (Django ORM không expose Lower() trong
        # partial unique index một cách thuận tiện ở 5.1, dùng raw SQL).
        # ---------------------------------------------------------------
        # BR-001: SKU unique toàn hệ thống, case-insensitive, scope row alive.
        # Cho phép tạo lại SKU đã soft-delete.
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX skus_variants_sku_lower_alive_uq
                ON skus_variants (LOWER(sku))
                WHERE deleted_at IS NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS skus_variants_sku_lower_alive_uq;",
        ),
        # Combo (product_id, material_code3, color_code3, size_preset) unique
        # per product, case-insensitive — không cho phép 2 variant cùng tổ hợp
        # axis trên 1 product (scope alive).
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX skus_variants_combo_lower_alive_uq
                ON skus_variants (
                    product_id,
                    LOWER(material_code3),
                    LOWER(color_code3),
                    LOWER(size_preset)
                )
                WHERE deleted_at IS NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS skus_variants_combo_lower_alive_uq;",
        ),
        # sequence_no unique per product (scope alive). Bảo vệ thêm cho
        # service select_for_update — nếu race lọt qua, IntegrityError thay
        # vì duplicate SKU.
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX skus_variants_prod_seq_alive_uq
                ON skus_variants (product_id, sequence_no)
                WHERE deleted_at IS NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS skus_variants_prod_seq_alive_uq;",
        ),
        # GIN trigram trên name — phục vụ icontains/search hiệu quả.
        migrations.RunSQL(
            sql="""
                CREATE INDEX skus_variants_name_trgm_idx
                ON skus_variants
                USING GIN (name gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS skus_variants_name_trgm_idx;",
        ),
        # GIN trigram trên sku — search input matching SKU prefix/substring.
        migrations.RunSQL(
            sql="""
                CREATE INDEX skus_variants_sku_trgm_idx
                ON skus_variants
                USING GIN (sku gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS skus_variants_sku_trgm_idx;",
        ),
        # GIN jsonb_path_ops trên attributes — query containment @>.
        migrations.RunSQL(
            sql="""
                CREATE INDEX skus_variants_attributes_gin_idx
                ON skus_variants
                USING GIN (attributes jsonb_path_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS skus_variants_attributes_gin_idx;",
        ),
    ]
